---
name: Build & Push Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: git.modulbit.eu

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
      options: --privileged
    services:
      docker:
        image: docker:dind
        options: --privileged
    permissions:
      contents: read
      packages: write
    steps:
      - name: Wait for Docker daemon
        run: |
          until docker info; do
            echo "Waiting for Docker daemon..."
            sleep 2
          done

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Forgejo Container Registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | \
            docker login git.modulbit.eu \
              --username smoliicek \
              --password-stdin

      - name: Build & Push image
        env:
          REPO: ${{ github.repository }}
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          IMAGE_BASE="git.modulbit.eu/$(echo "${REPO}" | tr '[:upper:]' '[:lower:]')"

          docker build \
            -t "${IMAGE_BASE}:latest" \
            -t "${IMAGE_BASE}:sha-${SHORT_SHA}" \
            .

          docker push "${IMAGE_BASE}:latest"
          docker push "${IMAGE_BASE}:sha-${SHORT_SHA}"
