---
name: Build & Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Forgejo Container Registry
        run: |
          docker login \
            -u ${{ github.actor }} \
            -p ${{ secrets.FORGEJO_TOKEN }} \
            git.modulbit.eu

      - name: Build image
        shell: bash
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          IMAGE_BASE="git.modulbit.eu/${{ github.repository }}"
          docker build \
            -t "${IMAGE_BASE}:latest" \
            -t "${IMAGE_BASE}:sha-${SHORT_SHA}" \
            .

      - name: Push image
        shell: bash
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          IMAGE_BASE="git.modulbit.eu/${{ github.repository }}"
          docker push "${IMAGE_BASE}:latest"
          docker push "${IMAGE_BASE}:sha-${SHORT_SHA}"
