---
name: Build & Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: fedora-44
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install packages
        run: |
          dnf install -y nodejs buildah

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Forgejo Container Registry
        run: |
          BUILDAH_ISOLATION=chroot buildah login -u ${{ github.actor }} -p ${{ secrets.FORGEJO_TOKEN }} git.modulbit.eu

      - name: Build image
        run: |
          BUILDAH_ISOLATION=chroot buildah build \
            -t git.modulbit.eu/${{ github.repository }}:latest \
            -t git.modulbit.eu/${{ github.repository }}:sha-${GITHUB_SHA::7} \
            .

      - name: Push image
        run: |
          BUILDAH_ISOLATION=chroot buildah push git.modulbit.eu/${{ github.repository }}:latest
          BUILDAH_ISOLATION=chroot buildah push git.modulbit.eu/${{ github.repository }}:sha-${GITHUB_SHA::7}
